import { Router } from 'express';
import { z } from 'zod';
import crypto from 'crypto';

export default function phase2(pool, auth) {
  const r = Router(); r.use(auth);
  const org = (q) => q.user.organizationId;
  const id = () => crypto.randomUUID();
  const addCalendarMonths=(date,months)=>{const result=new Date(`${date}T12:00:00`),day=result.getDate();result.setDate(1);result.setMonth(result.getMonth()+months);const last=new Date(result.getFullYear(),result.getMonth()+1,0).getDate();result.setDate(Math.min(day,last));return result.toISOString().slice(0,10)};
  r.use(async(q,s,n)=>{try{await pool.query(`UPDATE memberships SET status='expired' WHERE organization_id=? AND end_date<CURDATE() AND status IN ('active','pending')`,[q.user.organizationId]);await pool.query(`UPDATE members m SET m.status='inactive' WHERE m.organization_id=? AND m.deleted_at IS NULL AND EXISTS(SELECT 1 FROM memberships old_ms WHERE old_ms.member_id=m.id AND old_ms.end_date<CURDATE()) AND NOT EXISTS(SELECT 1 FROM memberships current_ms WHERE current_ms.member_id=m.id AND current_ms.status='active' AND CURDATE() BETWEEN current_ms.start_date AND current_ms.end_date)`,[q.user.organizationId]);n()}catch(e){n(e)}});
  r.get('/alerts/memberships',async(q,s,n)=>{try{const[x]=await pool.query(`SELECT ms.id,m.member_code,m.first_name,m.last_name,p.name plan_name,ms.end_date,ms.balance,DATEDIFF(ms.end_date,CURDATE()) days_remaining FROM memberships ms JOIN members m ON m.id=ms.member_id JOIN plans p ON p.id=ms.plan_id WHERE ms.organization_id=? AND ms.status IN ('active','pending') AND ms.end_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 7 DAY) ORDER BY ms.end_date ASC`,[org(q)]);s.json(x.map(a=>({...a,type:a.days_remaining===0?'expires_today':a.days_remaining===1?'expires_tomorrow':'expires_this_week'})))}catch(e){n(e)}});
  r.get('/dni/:number',async(q,s,n)=>{try{const dni=z.string().regex(/^\d{8}$/,'DNI debe tener 8 dígitos').parse(q.params.number);if(!process.env.FACTILIZA_TOKEN)return s.status(503).json({error:'Consulta DNI no configurada'});const response=await fetch(`https://api.factiliza.com/v1/dni/info/${dni}`,{headers:{Authorization:`Bearer ${process.env.FACTILIZA_TOKEN}`,Accept:'application/json'},signal:AbortSignal.timeout(10000)});const data=await response.json().catch(()=>null);if(!response.ok||!data?.success)return s.status(response.status===404?404:502).json({error:data?.message||'No se pudo consultar el DNI'});s.json({documentNumber:data.data.numero,firstName:data.data.nombres,lastName:[data.data.apellido_paterno,data.data.apellido_materno].filter(Boolean).join(' '),address:data.data.direccion_completa||null})}catch(e){n(e)}});
  r.get('/members', async (q,s,n) => { try { const [x]=await pool.query('SELECT * FROM members WHERE organization_id=? AND deleted_at IS NULL ORDER BY created_at DESC',[org(q)]); s.json(x); } catch(e){n(e)} });
  r.post('/members', async (q,s,n) => { try { const b=z.object({firstName:z.string().min(2),lastName:z.string().min(2),branchId:z.string().uuid(),documentNumber:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional()}).parse(q.body), memberId=id(), code='BF-'+Date.now().toString().slice(-7); await pool.query('INSERT INTO members(id,organization_id,branch_id,member_code,first_name,last_name,document_number,phone,email) VALUES(?,?,?,?,?,?,?,?,?)',[memberId,org(q),b.branchId,code,b.firstName,b.lastName,b.documentNumber||null,b.phone||null,b.email||null]); s.status(201).json({id:memberId,memberCode:code}); }catch(e){n(e)} });
  r.put('/members/:id', async(q,s,n)=>{try{const b=z.object({firstName:z.string().min(2),lastName:z.string().min(2),documentNumber:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional()}).parse(q.body); const[a]=await pool.query('UPDATE members SET first_name=?,last_name=?,document_number=?,phone=?,email=? WHERE id=? AND organization_id=? AND deleted_at IS NULL',[b.firstName,b.lastName,b.documentNumber||null,b.phone||null,b.email||null,q.params.id,org(q)]); if(!a.affectedRows)return s.status(404).json({error:'Cliente no encontrado'});s.json({ok:true});}catch(e){n(e)}});
  r.delete('/members/:id',async(q,s,n)=>{try{const[a]=await pool.query('UPDATE members SET deleted_at=NOW(),status="inactive" WHERE id=? AND organization_id=?',[q.params.id,org(q)]);if(!a.affectedRows)return s.status(404).json({error:'Cliente no encontrado'});s.status(204).end()}catch(e){n(e)}});
  r.get('/plans',async(q,s,n)=>{try{const[x]=await pool.query('SELECT * FROM plans WHERE organization_id=? ORDER BY status="active" DESC, price ASC',[org(q)]);s.json(x)}catch(e){n(e)}});
  r.post('/plans',async(q,s,n)=>{try{const b=z.object({name:z.string().min(2).max(120),price:z.number().positive(),durationMonths:z.number().int().min(1).max(12)}).parse(q.body);const planId=id();await pool.query('INSERT INTO plans(id,organization_id,name,price,duration_months,status) VALUES(?,?,?,?,?,?)',[planId,org(q),b.name,b.price,b.durationMonths,'active']);s.status(201).json({id:planId})}catch(e){n(e)}});
  r.put('/plans/:id',async(q,s,n)=>{try{const b=z.object({name:z.string().min(2).max(120),price:z.number().positive(),durationMonths:z.number().int().min(1).max(12)}).parse(q.body);const[a]=await pool.query('UPDATE plans SET name=?,price=?,duration_months=? WHERE id=? AND organization_id=?',[b.name,b.price,b.durationMonths,q.params.id,org(q)]);if(!a.affectedRows)return s.status(404).json({error:'Plan no encontrado'});s.json({ok:true})}catch(e){n(e)}});
  r.post('/plans/:id/toggle',async(q,s,n)=>{try{const[a]=await pool.query(`UPDATE plans SET status=IF(status='active','inactive','active') WHERE id=? AND organization_id=?`,[q.params.id,org(q)]);if(!a.affectedRows)return s.status(404).json({error:'Plan no encontrado'});s.json({ok:true})}catch(e){n(e)}});
  r.get('/trainers',async(q,s,n)=>{try{const[x]=await pool.query(`SELECT t.*,COUNT(a.id) assigned_members FROM trainers t LEFT JOIN trainer_assignments a ON a.trainer_id=t.id AND a.status='active' WHERE t.organization_id=? GROUP BY t.id ORDER BY t.status='active' DESC,t.first_name`,[org(q)]);s.json(x)}catch(e){n(e)}});
  r.post('/trainers',async(q,s,n)=>{try{const b=z.object({firstName:z.string().min(2),lastName:z.string().min(2),branchId:z.string().uuid(),documentNumber:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional(),specialties:z.string().optional(),availability:z.string().optional()}).parse(q.body),trainerId=id();await pool.query('INSERT INTO trainers(id,organization_id,branch_id,first_name,last_name,document_number,phone,email,specialties,availability) VALUES(?,?,?,?,?,?,?,?,?,?)',[trainerId,org(q),b.branchId,b.firstName,b.lastName,b.documentNumber||null,b.phone||null,b.email||null,b.specialties||null,b.availability||null]);s.status(201).json({id:trainerId})}catch(e){n(e)}});
  r.put('/trainers/:id',async(q,s,n)=>{try{const b=z.object({firstName:z.string().min(2),lastName:z.string().min(2),documentNumber:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional(),specialties:z.string().optional(),availability:z.string().optional()}).parse(q.body);const[a]=await pool.query('UPDATE trainers SET first_name=?,last_name=?,document_number=?,phone=?,email=?,specialties=?,availability=? WHERE id=? AND organization_id=?',[b.firstName,b.lastName,b.documentNumber||null,b.phone||null,b.email||null,b.specialties||null,b.availability||null,q.params.id,org(q)]);if(!a.affectedRows)return s.status(404).json({error:'Entrenador no encontrado'});s.json({ok:true})}catch(e){n(e)}});
  r.post('/trainers/:id/toggle',async(q,s,n)=>{try{const[a]=await pool.query(`UPDATE trainers SET status=IF(status='inactive','active','inactive') WHERE id=? AND organization_id=?`,[q.params.id,org(q)]);if(!a.affectedRows)return s.status(404).json({error:'Entrenador no encontrado'});s.json({ok:true})}catch(e){n(e)}});
  r.get('/trainers/:id/assignments',async(q,s,n)=>{try{const[x]=await pool.query(`SELECT a.*,m.member_code,m.first_name,m.last_name FROM trainer_assignments a JOIN members m ON m.id=a.member_id WHERE a.trainer_id=? AND a.organization_id=? AND a.status='active'`,[q.params.id,org(q)]);s.json(x)}catch(e){n(e)}});
  r.post('/trainer-assignments',async(q,s,n)=>{try{const b=z.object({trainerId:z.string().uuid(),memberId:z.string().uuid()}).parse(q.body);await pool.query('INSERT INTO trainer_assignments(id,organization_id,trainer_id,member_id) VALUES(?,?,?,?)',[id(),org(q),b.trainerId,b.memberId]);s.status(201).json({ok:true})}catch(e){n(e)}});
  r.get('/memberships',async(q,s,n)=>{try{const[x]=await pool.query(`SELECT ms.*,m.member_code,m.first_name,m.last_name,p.name plan_name FROM memberships ms JOIN members m ON m.id=ms.member_id JOIN plans p ON p.id=ms.plan_id WHERE ms.organization_id=? ORDER BY ms.created_at DESC`,[org(q)]);s.json(x)}catch(e){n(e)}});
  r.post('/memberships',async(q,s,n)=>{try{const b=z.object({memberId:z.string().uuid(),planId:z.string().uuid(),branchId:z.string().uuid(),startDate:z.string().date()}).parse(q.body);const[[p]]=await pool.query('SELECT * FROM plans WHERE id=? AND organization_id=?',[b.planId,org(q)]);if(!p)return s.status(404).json({error:'Plan no encontrado'});const endDate=addCalendarMonths(b.startDate,Number(p.duration_months));const membershipId=id();await pool.query('INSERT INTO memberships(id,organization_id,branch_id,member_id,plan_id,start_date,end_date,price,balance,status) VALUES(?,?,?,?,?,?,?,?,?,?)',[membershipId,org(q),b.branchId,b.memberId,b.planId,b.startDate,endDate,p.price,p.price,'pending']);s.status(201).json({id:membershipId,endDate,balance:p.price})}catch(e){n(e)}});
  r.post('/memberships/:id/:action',async(q,s,n)=>{try{const actions=['freeze','unfreeze','suspend','cancel'];if(!actions.includes(q.params.action))return s.status(400).json({error:'Acción inválida'});const status={freeze:'frozen',unfreeze:'active',suspend:'suspended',cancel:'cancelled'}[q.params.action];const[a]=await pool.query('UPDATE memberships SET status=? WHERE id=? AND organization_id=?',[status,q.params.id,org(q)]);if(!a.affectedRows)return s.status(404).json({error:'Membresía no encontrada'});await pool.query('INSERT INTO membership_events(id,membership_id,event_type,performed_by) VALUES(?,?,?,?)',[id(),q.params.id,q.params.action,q.user.sub]);s.json({status})}catch(e){n(e)}});
  r.get('/payments',async(q,s,n)=>{try{const[x]=await pool.query(`SELECT pr.*,m.member_code,m.first_name,m.last_name FROM payment_records pr JOIN members m ON m.id=pr.member_id WHERE pr.organization_id=? ORDER BY pr.paid_at DESC LIMIT 100`,[org(q)]);s.json(x)}catch(e){n(e)}});
  r.post('/payments',async(q,s,n)=>{const c=await pool.getConnection();try{const b=z.object({membershipId:z.string().uuid(),amount:z.number().positive(),method:z.enum(['cash','yape','plin','card','transfer','credit','mixed']),operationNumber:z.string().optional()}).parse(q.body);await c.beginTransaction();const[[m]]=await c.query('SELECT * FROM memberships WHERE id=? AND organization_id=? FOR UPDATE',[b.membershipId,org(q)]);if(!m)throw Error('Membresía no encontrada');if(b.amount>Number(m.balance))return s.status(400).json({error:'El monto excede el saldo pendiente'});const balance=Math.max(0,Number(m.balance)-b.amount);await c.query('INSERT INTO payment_records(id,organization_id,membership_id,member_id,amount,method,operation_number,received_by) VALUES(?,?,?,?,?,?,?,?)',[id(),org(q),m.id,m.member_id,b.amount,b.method,b.operationNumber||null,q.user.sub]);await c.query('UPDATE memberships SET balance=?,status=? WHERE id=?',[balance,balance===0?'active':'pending',m.id]);await c.commit();s.json({balance,status:balance===0?'active':'pending'})}catch(e){await c.rollback();n(e)}finally{c.release()}});
  r.get('/checkins',async(q,s,n)=>{try{const[x]=await pool.query(`SELECT c.*,m.member_code,m.first_name,m.last_name FROM checkins c JOIN members m ON m.id=c.member_id WHERE c.organization_id=? ORDER BY c.checkin_at DESC LIMIT 50`,[org(q)]);s.json(x)}catch(e){n(e)}});
  r.post('/checkins',async(q,s,n)=>{try{const b=z.object({identifier:z.string().min(1),branchId:z.string().uuid(),method:z.enum(['dni','member_code','qr','manual'])}).parse(q.body);const[[m]]=await pool.query('SELECT * FROM members WHERE organization_id=? AND (document_number=? OR member_code=?) AND status="active"',[org(q),b.identifier,b.identifier]);if(!m)return s.status(404).json({allowed:false,reason:'Cliente no encontrado'});const[[ms]]=await pool.query('SELECT * FROM memberships WHERE member_id=? AND branch_id=? AND status="active" AND CURDATE() BETWEEN start_date AND end_date',[m.id,b.branchId]);const allowed=!!ms;await pool.query('INSERT INTO checkins(id,organization_id,branch_id,member_id,membership_id,method,result,reason) VALUES(?,?,?,?,?,?,?,?)',[id(),org(q),b.branchId,m.id,ms?.id||null,b.method,allowed?'allowed':'denied',allowed?null:'Sin membresía activa']);s.json({allowed,reason:allowed?null:'Sin membresía activa',member:{id:m.id,name:m.first_name+' '+m.last_name}})}catch(e){n(e)}});
  return r;
}
