import {useState} from 'react';
import {BadgeCheck,CalendarDays,Edit3,Layers3,Plus,Power,Tag} from 'lucide-react';
import './plans-premium.css';
const money=n=>`S/ ${Number(n).toFixed(2)}`;
export default function PlansManager({plans,request,token,onDone}){
 const[plan,setPlan]=useState(null),[message,setMessage]=useState('');const months=p=>p.duration_months||Math.max(1,Math.min(12,Math.round(Number(p.duration_days||30)/30)));const active=plans.filter(p=>p.status==='active').length;
 async function save(e){e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get('name'),price:Number(f.get('price')),durationMonths:Number(f.get('durationMonths'))};try{await request(plan?.id?`/plans/${plan.id}`:'/plans',token,{method:plan?.id?'PUT':'POST',body:JSON.stringify(body)});setPlan(null);setMessage('Plan guardado correctamente');onDone()}catch(e){setMessage(e.message)}}
 async function toggle(id){try{await request(`/plans/${id}/toggle`,token,{method:'POST'});setMessage('Estado del plan actualizado');onDone()}catch(e){setMessage(e.message)}}
 return <><section className="plans-hero"><div><p>BLUE FIT · CONFIGURACIÓN COMERCIAL</p><h1>Planes de membresía</h1><span>Diseña modalidades, precios y vigencias para tu comunidad.</span></div><div className="plans-hero-stats"><span><Layers3 size={16}/><b>{plans.length}</b> planes</span><span><BadgeCheck size={16}/><b>{active}</b> activos</span></div><button onClick={()=>setPlan({})}><Plus size={17}/>Nuevo plan</button></section>{message&&<div className="notice">{message}</div>}<section className="plans-catalog"><div className="catalog-head"><div><p className="eyebrow">CATÁLOGO DE MEMBRESÍAS</p><h2>Modalidades disponibles</h2><small>Vigencias expresadas en meses calendario, de 1 a 12 meses.</small></div><span className="catalog-count">{plans.length} registros</span></div><div className="plans-grid premium-plans">{plans.map(p=><article className={`card plan premium-plan ${p.status}`} key={p.id}><div className="plan-topline"><span className={`plan-state ${p.status}`}><i/>{p.status==='active'?'Activo':'Inactivo'}</span><button className="plan-edit" title="Editar plan" onClick={()=>setPlan(p)}><Edit3 size={16}/></button></div><div className="plan-name"><span className="plan-symbol"><Tag size={19}/></span><h2>{p.name}</h2></div><div className="plan-price"><small>Precio de venta</small><b>{money(p.price)}</b></div><div className="plan-duration"><CalendarDays size={16}/><span><b>{months(p)}</b> {months(p)===1?'mes calendario':'meses calendario'}</span></div><div className="plan-actions"><button onClick={()=>setPlan(p)}><Edit3 size={15}/>Editar</button><button className={p.status==='active'?'pause':''} onClick={()=>toggle(p.id)}><Power size={15}/>{p.status==='active'?'Desactivar':'Activar'}</button></div></article>)}{!plans.length&&<div className="plans-empty">Aún no tienes planes. Crea la primera modalidad para empezar.</div>}</div></section>{plan&&<div className="modal"><form className="modal-box plan-form" onSubmit={save}><h2>{plan.id?'Editar plan':'Nuevo plan'}</h2><label>Nombre del plan<input name="name" placeholder="Ej. Membresía trimestral" defaultValue={plan.name||''} required/></label><label>Precio en soles<input name="price" type="number" min="0.01" step="0.01" placeholder="0.00" defaultValue={plan.price||''} required/></label><label>Duración en meses<input name="durationMonths" type="number" min="1" max="12" step="1" defaultValue={months(plan)} required/></label><small>Selecciona un periodo de 1 a 12 meses calendario.</small><div><button type="button" onClick={()=>setPlan(null)}>Cancelar</button><button>Guardar plan</button></div></form></div>}</>;
}
